---
name: load-generate

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - run: |
          pip install -r requirements.txt

      - run: python compile.py

      - run: |
          git fetch --tags --force && \
          latest=$(git tag --sort=creatordate | tail -1)

      - uses: peter-evans/create-pull-request@v6
        with:
          branch: load-data
          commit-message: 'new CFP data'
          delete-branch: true
          title: 'New CFP data'
          assignees: uchitsa
          base: master
